/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface GenerateNftInterface extends utils.Interface {
  functions: {
    "generateImage()": FunctionFragment;
    "getCountTokens()": FunctionFragment;
    "getDataUri(uint256)": FunctionFragment;
    "getNames()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "generateImage"
      | "getCountTokens"
      | "getDataUri"
      | "getNames"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "generateImage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCountTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDataUri",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "getNames", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "generateImage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCountTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDataUri", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNames", data: BytesLike): Result;

  events: {};
}

export interface GenerateNft extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GenerateNftInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    generateImage(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getCountTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDataUri(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { tokenImage: string }>;

    getNames(overrides?: CallOverrides): Promise<[string[]]>;
  };

  generateImage(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getCountTokens(overrides?: CallOverrides): Promise<BigNumber>;

  getDataUri(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getNames(overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    generateImage(overrides?: CallOverrides): Promise<void>;

    getCountTokens(overrides?: CallOverrides): Promise<BigNumber>;

    getDataUri(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getNames(overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    generateImage(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getCountTokens(overrides?: CallOverrides): Promise<BigNumber>;

    getDataUri(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNames(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    generateImage(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getCountTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDataUri(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNames(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
