/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface TestFileInterface extends utils.Interface {
  functions: {
    "generateBackground()": FunctionFragment;
    "getTrait(string)": FunctionFragment;
    "main(string,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "generateBackground" | "getTrait" | "main"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "generateBackground",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrait",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "main",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "generateBackground",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTrait", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "main", data: BytesLike): Result;

  events: {};
}

export interface TestFile extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestFileInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    generateBackground(
      overrides?: CallOverrides
    ): Promise<[string] & { image: string }>;

    getTrait(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { t: string[] }>;

    main(
      s: PromiseOrValue<string>,
      l: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  generateBackground(overrides?: CallOverrides): Promise<string>;

  getTrait(
    name: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  main(
    s: PromiseOrValue<string>,
    l: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    generateBackground(overrides?: CallOverrides): Promise<string>;

    getTrait(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    main(
      s: PromiseOrValue<string>,
      l: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    generateBackground(overrides?: CallOverrides): Promise<BigNumber>;

    getTrait(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    main(
      s: PromiseOrValue<string>,
      l: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    generateBackground(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTrait(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    main(
      s: PromiseOrValue<string>,
      l: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
